### ISSUE TITLE
Not Working ! PS. I do not know any coding/programming, just followed your instructions ....

### ISSUE THREAD

**Issue by Roozb** [SRvSaha/CoWinVaccineSlotFinder#24] opened 2021-05-14 19:44 UTC
![C__Users_Roozbeh_Desktop_CoWinReleases_CoWin Core exe 15-05-2021 1_06_58](https://user-images.githubusercontent.com/84204114/118321124-cc855780-b51a-11eb-9cf7-e747fea21cbb.png)

**Comment by SRvSaha** [comment] 2021-05-15 04:01
Hi @Roozb, on checking your scenario, observed that you have some issue with the following line of the config file:
`"IsSearchToBeDoneByPINCode": true`

Seems like you have pressed ENTER key in the input.
Can you please share your config file after removing the confidential information like beneficiary id and mobile number to help us resolve your issue quicker?

Meanwhile you can try again with the suggestion above and inform if it work. Hope you are using the latest version: (v3.0.0)[https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest]

**Comment by Tnu02** [comment] 2021-05-15 13:11
App crashed as soon as the slot got available

**Comment by Roozb** [comment] 2021-05-15 13:28
I have *** the last few digits to prevent privacy 

> Hi @Roozb, on checking your scenario, observed that you have some issue with the following line of the config file:
> `"IsSearchToBeDoneByPINCode": true`
> 
> Seems like you have pressed ENTER key in the input.
> Can you please share your config file after removing the confidential information like beneficiary id and mobile number to help us resolve your issue quicker?
> 
> Meanwhile you can try again with the suggestion above and inform if it work. Hope you are using the latest version: [v3.0.0](https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest)


![appsettings - Notepad 15-05-2021 18_56_28](https://user-images.githubusercontent.com/84204114/118362893-541ca600-b5af-11eb-8bd8-f5a4011f6a80.png)

**Comment by SRvSaha** [comment] 2021-05-15 13:59
> 
> 
> App crashed as soon as the slot got available

Hi @Tnu02, sorry that happened, Can you share the config so that I can check from my side. 
Is slot available now as well?
Also, can you tell me what exactly happened like : Did your Captcha Pop Up? Did you get NOTIFIER BEEP BEEP before entering Captcha?

**Comment by SRvSaha** [comment] 2021-05-15 14:06
> 
> 
> I have *** the last few digits to prevent privacy
> 
> > Hi @Roozb, on checking your scenario, observed that you have some issue with the following line of the config file:
> > `"IsSearchToBeDoneByPINCode": true`
> > Seems like you have pressed ENTER key in the input.
> > Can you please share your config file after removing the confidential information like beneficiary id and mobile number to help us resolve your issue quicker?
> > Meanwhile you can try again with the suggestion above and inform if it work. Hope you are using the latest version: [v3.0.0](https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest)
> 
> ![appsettings - Notepad 15-05-2021 18_56_28](https://user-images.githubusercontent.com/84204114/118362893-541ca600-b5af-11eb-8bd8-f5a4011f6a80.png)

Hi @Roobz, see you have a missing quote in the highlighted area:
![image](https://user-images.githubusercontent.com/13312352/118364099-a7ddbe00-b5b4-11eb-8a8c-e9fd4b5d2783.png)

Please Replace `"Thane-2nd:` with `"Thane-2nd": ` and it should fix your issue. Let me know if that fixes your issue.

In Case, I could help you, feel free to Star the repo and share it with your buddies! Also share your feedback by comment/share/like in the associated LinkedIn Post (https://www.linkedin.com/feed/update/urn:li:activity:6796093424492720128/) That'll be used as References/Testimonials in the Application and will increase the credibility of the App.

**Comment by Tnu02** [comment] 2021-05-15 14:14
> > App crashed as soon as the slot got available
> 
> Hi @Tnu02, sorry that happened, Can you share the config so that I can check from my side.
> Is slot available now as well?
> Also, can you tell me what exactly happened like : Did your Captcha Pop Up? Did you get NOTIFIER BEEP BEEP before entering Captcha? Also, what is the version of the App you are using?

I was not sure but as soon as the slots are avialble there was some message on the app and it got crashed without even asked for captcha also no beep and no captcha pop up..
please tell me a way to share my config file.

I was using 3.0 version

**Comment by SRvSaha** [comment] 2021-05-15 14:17
@Tnu02 Please share here as attachment after removing the mobile number and beneficiary details. I will try from my side. 
Just some more info: Could you get the BEEP BEEP OTP Notification when OTP was sent to your Registered Mobile Number?
Also, when the App crashed, did you retry after that? Can you retry again and see if it still crashes.
Also. please provide your system windows version

**Comment by Tnu02** [comment] 2021-05-15 14:26
> @Tnu02 Please share here as attachment after removing the mobile number and beneficiary details. I will try from my side.
> Just some more info: Could you get the BEEP BEEP OTP Notification when OTP was sent to your Registered Mobile Number?
> Also, when the App crashed, did you retry after that? Can you retry again and see if it still crashes.
> Also. please provide your system windows version

Yes, i got the beep sound for the otp and after entering it starts checking for slots.
I tried 2 time with the app but both the time it got crashed so i tried manually but no luck today.
I am using windows 10 Pro

![Config](https://user-images.githubusercontent.com/83922100/118364747-600c6600-b5b7-11eb-83c0-0b15ed98385e.jpg)

**Comment by SRvSaha** [comment] 2021-05-15 14:29
> 
> 
> @Tnu02 Please share here as attachment after removing the mobile number and beneficiary details. I will try from my side.
> Just some more info: Could you get the BEEP BEEP OTP Notification when OTP was sent to your Registered Mobile Number?
> Also, when the App crashed, did you retry after that? Can you retry again and see if it still crashes.
> Also. please provide your system windows version

Also, if you can provide the system error diagnostic information from your machine, it would be best to help resolve the issue.

How to do that?

Go to Event Viewer
![image](https://user-images.githubusercontent.com/13312352/118364821-af529680-b5b7-11eb-8982-ca231bf6fc1f.png)

And then Under Windows Logs, go to Application.

![image](https://user-images.githubusercontent.com/13312352/118364835-c2fdfd00-b5b7-11eb-92b4-974c5133d7fa.png)

After that on the right side, there is a filter current log, filter the Event Sources for .NET Runtime
![image](https://user-images.githubusercontent.com/13312352/118364852-df019e80-b5b7-11eb-8ef7-e3d2cfb897af.png)

Once that is done, you will see the error logs. Share the details like this from there, which will have all the information regarding the crash if that has happened due to some bug in the code or some unexpected behaviour.

![image](https://user-images.githubusercontent.com/13312352/118364889-fa6ca980-b5b7-11eb-8c1b-045a643b7da1.png)

Please share these details ASAP @Tnu02

**Comment by SRvSaha** [comment] 2021-05-15 14:34
> 
> 
> > @Tnu02 Please share here as attachment after removing the mobile number and beneficiary details. I will try from my side.
> > Just some more info: Could you get the BEEP BEEP OTP Notification when OTP was sent to your Registered Mobile Number?
> > Also, when the App crashed, did you retry after that? Can you retry again and see if it still crashes.
> > Also. please provide your system windows version
> 
> Yes, i got the beep sound for the otp and after entering it starts checking for slots.
> I tried 2 time with the app but both the time it got crashed so i tried manually but no luck today.
> I am using windows 10 Pro
> 
> ![Config](https://user-images.githubusercontent.com/83922100/118364747-600c6600-b5b7-11eb-83c0-0b15ed98385e.jpg)

Sorry to hear that.

On first observation, I could see that Vaccination Centre Name is not correct.

` "VaccinationCentreName": <USE_EITHER_PROPER_VACCINATION_CENTRE_NAME_OR_LEAVE_IT_BLANK>`

Check  #21, VaccinationCentreName should be the like the name highlighted in Yellow in the issue description.

**Comment by Tnu02** [comment] 2021-05-15 14:45
> > @Tnu02 Please share here as attachment after removing the mobile number and beneficiary details. I will try from my side.
> > Just some more info: Could you get the BEEP BEEP OTP Notification when OTP was sent to your Registered Mobile Number?
> > Also, when the App crashed, did you retry after that? Can you retry again and see if it still crashes.
> > Also. please provide your system windows version
> 
> Also, if you can provide the system error diagnostic information from your machine, it would be best to help resolve the issue.
> 
> How to do that?
> 
> Go to Event Viewer
> ![image](https://user-images.githubusercontent.com/13312352/118364821-af529680-b5b7-11eb-8982-ca231bf6fc1f.png)
> 
> And then Under Windows Logs, go to Application.
> 
> ![image](https://user-images.githubusercontent.com/13312352/118364835-c2fdfd00-b5b7-11eb-92b4-974c5133d7fa.png)
> 
> After that on the right side, there is a filter current log, filter the Event Sources for .NET Runtime
> ![image](https://user-images.githubusercontent.com/13312352/118364852-df019e80-b5b7-11eb-8ef7-e3d2cfb897af.png)
> 
> Once that is done, you will see the error logs. Share the details like this from there, which will have all the information regarding the crash if that has happened due to some bug in the code or some unexpected behaviour.
> 
> ![image](https://user-images.githubusercontent.com/13312352/118364889-fa6ca980-b5b7-11eb-8c1b-045a643b7da1.png)
> 
> Please share these details ASAP @Tnu02

Sharing error
![Error1](https://user-images.githubusercontent.com/83922100/118365393-3e60ae00-b5ba-11eb-9c85-eded7ca8c357.jpg)
![Error2](https://user-images.githubusercontent.com/83922100/118365395-41f43500-b5ba-11eb-883f-ad7cf757af7f.jpg)
![Error3](https://user-images.githubusercontent.com/83922100/118365396-43bdf880-b5ba-11eb-8e29-fa1184b36859.jpg)
![Error4](https://user-images.githubusercontent.com/83922100/118365397-44ef2580-b5ba-11eb-89af-b4c975cf97a3.jpg)
![Error5](https://user-images.githubusercontent.com/83922100/118365399-46205280-b5ba-11eb-9116-9a2365778335.jpg)

**Comment by Tnu02** [comment] 2021-05-15 14:46
> > > @Tnu02 Please share here as attachment after removing the mobile number and beneficiary details. I will try from my side.
> > > Just some more info: Could you get the BEEP BEEP OTP Notification when OTP was sent to your Registered Mobile Number?
> > > Also, when the App crashed, did you retry after that? Can you retry again and see if it still crashes.
> > > Also. please provide your system windows version
> > 
> > 
> > Yes, i got the beep sound for the otp and after entering it starts checking for slots.
> > I tried 2 time with the app but both the time it got crashed so i tried manually but no luck today.
> > I am using windows 10 Pro
> > ![Config](https://user-images.githubusercontent.com/83922100/118364747-600c6600-b5b7-11eb-83c0-0b15ed98385e.jpg)
> 
> @Tnu02
> 
> Sorry to hear that.
> 
> On first observation, I could see that Vaccination Centre Name is not correct.
> 
> ` "VaccinationCentreName": <USE_EITHER_PROPER_VACCINATION_CENTRE_NAME_OR_LEAVE_IT_BLANK>`
> 
> Check #21, VaccinationCentreName should be the like the name highlighted in Yellow in the issue description.

Corrected that thank you...

Also thank you to look into the issue so actively

**Comment by SRvSaha** [comment] 2021-05-15 14:54
@Tnu02 As per the error screenshots, I could see that you had set duplicate values inside of PINCodes where Udaipur was duplicate and hence the application crashed. However the current config you have shared has proper names.

```
{
"PINCodes":
{
"Udaipur": XXXXXX,
"Udaipur": YYYYYY
}
}
```
I'd suggest you keep some arbitrary names, and search again by setting "MinimumVaccineAvailability": 0, so that you can check if you application works or not. 

Event though booking will not happen, but you can see if you are getting the slots and then proceeding for captcha.
You'll get Already Booked error.
If you still get some error, share it here.

**Comment by SRvSaha** [comment] 2021-05-15 15:00
> 
> 
> @Tnu02 As per the error screenshots, I could see that you had set duplicate values inside of PINCodes where Udaipur was duplicate and hence the application crashed. However the current config you have shared has proper names.
> 
> ```
> {
> "PINCodes":
> {
> "Udaipur": XXXXXX,
> "Udaipur": YYYYYY
> }
> }
> ```
> 
> I'd suggest you keep some arbitrary names, and search again by setting "MinimumVaccineAvailability": 0, so that you can check if you application works or not.
> 
> Event though booking will not happen, but you can see if you are getting the slots and then proceeding for captcha.
> You'll get Already Booked error.
> If you still get some error, share it here.

@Tnu02 You should be getting something like this, it is working fine with me:
![image](https://user-images.githubusercontent.com/13312352/118365958-6224f380-b5bc-11eb-8b87-3fa4e5c20e54.png)

**Comment by Tnu02** [comment] 2021-05-15 15:01
> > @Tnu02 As per the error screenshots, I could see that you had set duplicate values inside of PINCodes where Udaipur was duplicate and hence the application crashed. However the current config you have shared has proper names.
> > ```
> > {
> > "PINCodes":
> > {
> > "Udaipur": XXXXXX,
> > "Udaipur": YYYYYY
> > }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'd suggest you keep some arbitrary names, and search again by setting "MinimumVaccineAvailability": 0, so that you can check if you application works or not.
> > Event though booking will not happen, but you can see if you are getting the slots and then proceeding for captcha.
> > You'll get Already Booked error.
> > If you still get some error, share it here.
> 
> @Tnu02 You should be getting something like this, it is working fine with me:
> ![image](https://user-images.githubusercontent.com/13312352/118365958-6224f380-b5bc-11eb-8b87-3fa4e5c20e54.png)

Checking.. Thank you so much for your quick responses :) :)

**Comment by Tnu02** [comment] 2021-05-15 15:03
@SRvSaha Checked... working fine now.. Will again try tomorrow for booking.
Thank u so much...

**Comment by SRvSaha** [comment] 2021-05-15 15:04
@Tnu02 Awesome. In Case, I could help you, feel free to Star the repo and share it with your buddies! Also share your feedback by comment/share/like in the associated LinkedIn Post (https://www.linkedin.com/feed/update/urn:li:activity:6796093424492720128/) That'll be used as References/Testimonials in the Application and will increase the credibility of the App. Closing the Issue.

**Closed by SRvSaha** 2021-05-15 15:04 UTC
Labels: question

**Comment by Tnu02** [comment] 2021-05-16 09:47
Hey @SRvSaha sorry to disturb you again but have I doubt regarding pin code and district.. Do i need to put a , if I have single district and pin code like "district" : xxxxxx, or just xxxxx and same for district!!

**Comment by SRvSaha** [comment] 2021-05-16 10:01
You don’t need a comma. For multiple districts/pins you need comma separator.

Also, there are some changes made by CoWin, I am made the fix. Shall deploy a new version ASAP. Use the latest one @Tnu02

**Comment by Tnu02** [comment] 2021-05-16 10:03
> You don’t need a comma. For multiple districts/pins you need comma separator.
> 
> Also, there are some changes made by CoWin, I am made the fix. Shall deploy a new version ASAP. Use the latest one @Tnu02 

Oh thanks 😊

**Comment by SRvSaha** [comment] 2021-05-16 10:06
@Tnu02 Please NOTE, If you want to search only by PIN which is by default, keep “IsSearchToBeDoneByPINCode” : true, similarly if you want to search only for District then “IsSearchToBeDoneByDistrict” : true.
In case you want to do both, where preference is on PIN code, keep both as true.

**Comment by Tnu02** [comment] 2021-05-16 10:11
> @Tnu02 Please NOTE, If you want to search only by PIN which is by default, keep “IsSearchToBeDoneByPINCode” : true, similarly if you want to search only for District then “IsSearchToBeDoneByDistrict” : true.
> In case you want to do both, where preference is on PIN code, keep both as true.

Gotcha Thanks :) And I can write like "PINCodes": { "Udaipur-1st": XXXXX} or just "Udaipur": XXXXXX..
Also do let us know once u are done with the deployment. 👍

**Comment by SRvSaha** [comment] 2021-05-16 11:12
It's well mentioned in the ReadMe. 
You can't add multiple DateToSearch, by Default it searches for DateGiven + upto 7 days
Please check that. 
@Tnu02

**Comment by Tnu02** [comment] 2021-05-16 11:16
> It's well mentioned in the ReadMe.
> You can't add multiple DateToSearch, by Default it searches for DateGiven + upto 7 days
> Please check that.
> @Tnu02

Thanks... Can I use 3.0 version for my booking as slots are going to open at 5 PM

**Comment by SRvSaha** [comment] 2021-05-16 11:22
You can use. But you might see that Slots are available yet Booking is not getting done. This is due to changes in the Internal API of COWIN. @Tnu02

**Comment by Roozb** [comment] 2021-05-16 15:40
SRvSaha I have made the changes as suggested by you & it is working fine, now with the new updates from the cowin official site will your application work now ? also when you provide the new updated file from your side will we have to make changes in the appsettings file from our side too ?

**Comment by SRvSaha** [comment] 2021-05-16 15:42
Hi @Roozb, application will work with some T&C's as mentioned in #27.
New Version v4.0.0 will be deployed tonight, WIP

**Comment by Roozb** [comment] 2021-05-16 15:47
Wow , thanks a lot for the speedy reply. Awaiting for the latest version ..

**Comment by SRvSaha** [comment] 2021-05-17 11:16
@Roozb  @Tnu02 @iSatishYadav  @priyanka1111 Version 4.0.0 is out now. Thanks for your patience. Check it out: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest

**Comment by Roozb** [comment] 2021-05-17 22:42
HI SRvSAha , tried the latest version works perfectly . Just wanted to clarify that the app suggested that both "IsSearchToBeDoneByPINCode"  and  "IsSearchToBeDoneByDistrict" remain "true" , is that allright ?? Hence I have made them both true. Thanks for the latest updates.

**Comment by SRvSaha** [comment] 2021-05-18 02:19
@Roozb Hi, thanks for the feedback, could you book slot?

The App suggested that because you changed values of district but forgot to change IsSearchToBeDoneByDistrict. If you don’t want to search by district and only by PIN, no chnage is require in IsSearchToBeDoneByDistrict and district. Let it be as it is. It is alright to keep both as true, at that tike preferred will be slot by PIN and then by District, not an issue.

Since others nave reported issues as it isn’t working properly, please share it it worked for you.
